# Generated by Django 4.1.7 on 2023-09-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_patientinfo_patientname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='PatientId',
            field=models.CharField(max_length=50),
        ),
    ]
