# Generated by Django 5.0.6 on 2024-07-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='study_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dicomdata',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
