# Generated by Django 5.0.6 on 2024-07-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_dicomdata_study_uid_alter_dicomdata_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicomdata',
            old_name='study_uid',
            new_name='study_id',
        ),
    ]
