# Generated by Django 5.1 on 2024-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rename_study_uid_dicomdata_study_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayreport',
            name='pdf_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
